### PR TITLE
support json-ld, fix issue #28

### PR DESCRIPTION
**Pull request by fogfish**

### CODE REVIEW

**Comment by gsf** [comment]
I'm surprised to see commits on this old project, but this is great. I'll add tests and update whiskers.min.js and merge.

**Comment by fogfish** [comment]
This is like an old wine :-)
I am experimenting with pure functional approach in Web / UI development.
whiskers is great to make a pure function for template rendering. If you are interesting on subject you might look here https://github.com/fogfish/monad.js

**Comment by fogfish** [comment]
bump!

**Comment by gsf** [comment]
Finally! Sorry for the lag. Also published in npm.

**Pull request merged**
